name: Deploy to Lambda

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Use the appropriate Python version
          
      - name: Deploy to Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
        run: |
          aws lambda update-function-code \
            --function-name simple-python-project \
            --zip-file fileb://simple-python-project.zip
