name: Deploy to Lambda

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Python Script
        run: |
          # Zip the Python script and any necessary files
          zip -r simple-python-project.zip lambda_function.py

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Use the appropriate Python version
          
      - name: Deploy to Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
          AWS_DEFAULT_OUTPUT: json
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws lambda update-function-code \
            --function-name simple-python-project \
            --zip-file fileb://simple-python-project.zip
